In [8]:
import numpy as np

a=np.array([[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12],
           [13,14,15,16]])
print("a =",a)

b = int(input("Enter no of rows:"))
c = int(input("Enter no of columns:"))

N4 = []

if b+1 < 5:
    N4.append(a[b+1,c])
if b-1 >=0:
    N4.append(a[b-1,c])
if c+1 <5:
    N4.append(a[b,c+1])    
if c-1 >= 0:
    N4.append(a[b,c-1])

print("N4:",N4)

Nd=[]

if b+1 <5 and c+1<5:
    Nd.append(a[b+1,c+1])
if b+1 <5 and c-1 >=0:
    Nd.append(a[b+1,c-1])
if b-1 >=0 and c+1 <5:
    Nd.append(a[b-1,c+1])
if b-1 >=0 and c-1 >=0:
    Nd.append(a[b-1,c-1])

print("Nd:",Nd)
N8=[]
if b+1<5:
    N8.append(a[b+1,c])
if b-1>=0:
    N8.append(a[b-1,c])
if c+1<5:
    N8.append(a[b,c+1])
if c-1>=0:
    N8.append(a[b,c-1])
if b+1<5 and c+1<5:
    N8.append(a[b+1,c+1])
if b+1<5 and c-1>=0:
    N8.append(a[b+1,c-1])
if b-1>=0 and c+1<5:
    N8.append(a[b-1,c+1])
if b-1>=0 and c-1>=0:
    N8.append(a[b-1,c-1])
print("\nNeighbours of N8: ",N8)




a = [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
N4: [15, 7, 12, 10]
Nd: [16, 14, 8, 6]

Neighbours of N8:  [15, 7, 12, 10, 16, 14, 8, 6]
